# Dejima Homebrew formula (binary) — AUTO-GENERATED by scripts/gen-homebrew-formula.sh.
#
# Do not hand-edit the copy in the tap repo: the release workflow regenerates and
# pushes it to github.com/aoos/homebrew-dejima/Formula/dejima.rb on every tag.
# To change structure (deps, caveats, …), edit the generator script and re-run it.
#
#   brew install aoos/dejima/dejima          # pinned binary (this formula)
#   brew install --HEAD aoos/dejima/dejima   # build from source off master
#
# Unix archives carry `dejima` + `dejimad`; the daemon only runs on a Unix host.
class Dejima < Formula
  desc "Substrate for multi-device AI agent workflows"
  homepage "https://dejima.tech"
  version "0.8.64"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_arm64.tar.gz"
      sha256 "dc16db71f39b28edb99407b402c93e1275452bf48d1717f97f7176f8c33aae50"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_amd64.tar.gz"
      sha256 "d1a1b4ce86b3b82e620174bf7d3b6acc9a2854436d003ac9ad2f771b91a89b41"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_arm64.tar.gz"
      sha256 "0cd62983fbd574919cf36132454c044eab218b58af71f45d8204d7f6ae2ab780"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_amd64.tar.gz"
      sha256 "ff8e5be7b982299c2ec3287af800fc967ee77ec2ed90923232bddb448c67654a"
    end
  end

  head "https://github.com/aoos/dejima.git", branch: "master"

  depends_on "go" => :build if build.head?

  def install
    if build.head?
      ENV["GOFLAGS"] = "-trimpath"
      system "make", "build"
      bin.install "bin/dejima", "bin/dejimad"
    else
      # Released tarball: client always present; daemon only in Unix archives.
      bin.install "dejima"
      bin.install "dejimad" if File.exist?("dejimad")
    end
  end

  def caveats
    <<~CAVEAT
      Dejima needs a Docker runtime to run the daemon + islands. On macOS:

        brew install --cask docker-desktop        # Docker Desktop (recommended)
        brew install --cask orbstack      # or OrbStack (personal-use license)
        brew install colima docker        # or colima (CLI-only, OSS)

      Then build the island image and register the daemon from a checkout:

        make image && dejima service install

      Client-only (a laptop driving a remote daemon)? Skip Docker and just:

        export DEJIMA_HOST=your-host.tailnet:7273
        dejima connect <island>
    CAVEAT
  end

  test do
    assert_match "dejima", shell_output("#{bin}/dejima --version")
  end
end
