# Dejima Homebrew formula (binary) — AUTO-GENERATED by scripts/gen-homebrew-formula.sh.
#
# Do not hand-edit the copy in the tap repo: the release workflow regenerates and
# pushes it to github.com/aoos/homebrew-dejima/Formula/dejima.rb on every tag.
# To change structure (deps, caveats, …), edit the generator script and re-run it.
#
#   brew install aoos/dejima/dejima          # pinned binary (this formula)
#   brew install --HEAD aoos/dejima/dejima   # build from source off master
#
# Unix archives carry `dejima` + `dejimad`; the daemon only runs on a Unix host.
class Dejima < Formula
  desc "Substrate for multi-device AI agent workflows"
  homepage "https://dejima.tech"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_arm64.tar.gz"
      sha256 "05de3bb2f606cbfbdf65cc58990727dc67c2ce1eafadb1046ab50ae0c5f84ffb"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_amd64.tar.gz"
      sha256 "21d39e3abf1fd5ed25e3a1371a4d04dda7858f595893120d5358d69bc8db70d0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_arm64.tar.gz"
      sha256 "b1939127d4f750e2c12b55d3beae3174e77d8a6440c0bb9e34abd9b24dd76b7e"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_amd64.tar.gz"
      sha256 "4222d7b034b38fea3cebaf0f8a8acbe9ea395bbd8ec013c18226e0679bf73f5a"
    end
  end

  head "https://github.com/aoos/dejima.git", branch: "master"

  depends_on "go" => :build if build.head?

  def install
    if build.head?
      ENV["GOFLAGS"] = "-trimpath"
      system "make", "build"
      bin.install "bin/dejima", "bin/dejimad"
    else
      # Released tarball: client always present; daemon only in Unix archives.
      bin.install "dejima"
      bin.install "dejimad" if File.exist?("dejimad")
    end
  end

  def caveats
    <<~CAVEAT
      Dejima needs a Docker runtime to run the daemon + islands. On macOS:

        brew install --cask docker        # Docker Desktop (recommended)
        brew install --cask orbstack      # or OrbStack (personal-use license)
        brew install colima docker        # or colima (CLI-only, OSS)

      Then build the island image and register the daemon from a checkout:

        make image && dejima service install

      Client-only (a laptop driving a remote daemon)? Skip Docker and just:

        export DEJIMA_HOST=your-host.tailnet:7273
        dejima connect <island>
    CAVEAT
  end

  test do
    assert_match "dejima", shell_output("#{bin}/dejima --version")
  end
end
