# Dejima Homebrew formula (binary) — AUTO-GENERATED by scripts/gen-homebrew-formula.sh.
#
# Do not hand-edit the copy in the tap repo: the release workflow regenerates and
# pushes it to github.com/aoos/homebrew-dejima/Formula/dejima.rb on every tag.
# To change structure (deps, caveats, …), edit the generator script and re-run it.
#
#   brew install aoos/dejima/dejima          # pinned binary (this formula)
#   brew install --HEAD aoos/dejima/dejima   # build from source off master
#
# Unix archives carry `dejima` + `dejimad`; the daemon only runs on a Unix host.
class Dejima < Formula
  desc "Substrate for multi-device AI agent workflows"
  homepage "https://dejima.tech"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_arm64.tar.gz"
      sha256 "48767d0ff80967755f52cae9204930628627796b7a16c12ded0862bbf3f1fdfb"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_amd64.tar.gz"
      sha256 "7de6b5f08787e5227337018c4383c0b861270c1de31246401ff0489611fd3467"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_arm64.tar.gz"
      sha256 "4ed0a132b3600db3a2b8fc1fc62826540f23ed0359249e1c96d0568469346211"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_amd64.tar.gz"
      sha256 "f521f360e83d0a7a6e1d6c0b5b134ac5ceadbf49959bfa7455668b125a1b8399"
    end
  end

  head "https://github.com/aoos/dejima.git", branch: "master"

  depends_on "go" => :build if build.head?

  def install
    if build.head?
      ENV["GOFLAGS"] = "-trimpath"
      system "make", "build"
      bin.install "bin/dejima", "bin/dejimad"
    else
      # Released tarball: client always present; daemon only in Unix archives.
      bin.install "dejima"
      bin.install "dejimad" if File.exist?("dejimad")
    end
  end

  def caveats
    <<~CAVEAT
      Dejima needs a Docker runtime to run the daemon + islands. On macOS:

        brew install --cask docker        # Docker Desktop (recommended)
        brew install --cask orbstack      # or OrbStack (personal-use license)
        brew install colima docker        # or colima (CLI-only, OSS)

      Then build the island image and register the daemon from a checkout:

        make image && dejima service install

      Client-only (a laptop driving a remote daemon)? Skip Docker and just:

        export DEJIMA_HOST=your-host.tailnet:7273
        dejima connect <island>
    CAVEAT
  end

  test do
    assert_match "dejima", shell_output("#{bin}/dejima --version")
  end
end
